name: CI Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use latest node.js version
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Lint
        if: success()
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Deploy
        if: success()
        uses: serverless/github-action@v1.53.0
        with:
          args: deploy --stage staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
